# Generated by Django 5.0.6 on 2024-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_is_sale_remove_category_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_sample',
            field=models.ImageField(default='', max_length=4, upload_to='uploads/product/'),
        ),
    ]
