# Generated by Django 5.0.6 on 2024-06-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_sample',
        ),
    ]
