# Generated by Django 5.0.6 on 2024-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_sample',
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample1',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample2',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample3',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample4',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
    ]
