# Generated by Django 5.0.6 on 2024-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_image_sample1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(default='', upload_to='uploads/product/'),
        ),
    ]
