# Generated by Django 5.0.6 on 2024-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_sample1',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample2',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample3',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_sample4',
            field=models.ImageField(default='', upload_to='uploads/product'),
        ),
    ]
