# Generated by Django 5.0.6 on 2024-06-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image_sample1_product_image_sample2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_sample1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_sample2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_sample3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_sample4',
        ),
    ]
